### ISSUE TITLE
it woud be nice if ojo would noch crash when started with no arguments

### ISSUE THREAD

**Issue by revast** [peterlevi/ojo#42]
better would be to open a file-selector to let the user browse to a file.

**Comment by peterlevi** [comment]
It is not supposed to crash, it is supposed to start browsing in the last folder you were in, or in ~/Pictures, when started for the first time. Please provide logs from the crash.

**Comment by revast** [comment]
Traceback (most recent call last):
  File "/usr/bin/ojo", line 42, in <module>
    ojo.Ojo()
  File "/usr/lib/python3/dist-packages/ojo/ojo.py", line 147, in __init__
    self.after_quick_start()
  File "/usr/lib/python3/dist-packages/ojo/ojo.py", line 518, in after_quick_start
    self.thumbs.start()
  File "/usr/lib/python3/dist-packages/ojo/thumbs.py", line 39, in start
    self.pool = multiprocessing.Pool(processes=multiprocessing.cpu_count() - 1)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 168, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError
: Number of processes must be at least 1

**Comment by peterlevi** [comment]
Are you on a single-core machine? What's the output of `cat /proc/cpuinfo | grep processor | wc -l` ?

**Comment by peterlevi** [comment]
I committed a fix and started a new build, it should be in the PPA fairly soon, please try to apt update/upgrade in an hour.
